{% set org = "mit-crpg" %}
{% set name = "openmc" %}
{% set version = "0.9.0" %}
{% set sha256 = "d82d280eee1ba3ba3450d66f8c56fc5c7ce4e7f53714eafb4053869b4ee76cd7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - toolchain
    - cmake
    - pkg-config
    - gcc
    - hdf5 1.8.18|1.8.18.*
    - git
    - setuptools
    - numpy >=1.9
    - cython
    - matplotlib
    - h5py
  run:
    - libgcc
    - libgfortran
    - hdf5 1.8.18|1.8.18.*
    - python >=2.7
    - six
    - numpy >=1.9
    - h5py
    - scipy
    - pandas
    - matplotlib
    - lxml
    - uncertainties

test:
  commands:
    - test -f "${PREFIX}/bin/openmc"
    - openmc --version

about:
  home: http://openmc.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary: 'OpenMC Monte Carlo Code'
  description: |
    OpenMC is a Monte Carlo particle transport simulation code focused on
    neutron criticality calculations. It is capable of simulating 3D models
    based on constructive solid geometry with second-order surfaces. The
    particle interaction data is based on ACE format cross sections, also
    used in the MCNP and Serpent Monte Carlo codes.
  doc_url: http://openmc.readthedocs.io
  dev_url: https://github.com/mit-crpg/openmc

extra:
  recipe-maintainers:
    - scopatz
    - paulromano
