{% set org = "openmc-dev" %}
{% set name = "openmc" %}
{% set version = "0.14.0" %}
{% set sha256 = "20ac92cc8d37a8c1180ae2df9f1dd1158f188cbf724ae64c9642db6199f3ee3f" %}
{% set build = 0 %}

# define mpi
{% set mpi = mpi or 'nompi' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
    fn: {{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - url: https://github.com/zeux/pugixml/archive/41b6ff21c455865bb8ef67c5952b7f895b62bacc.tar.gz
    sha256: b145725a8eb17081783d3e0b7118ec825140f8972da5ab5e15c1d051810c1a93
    folder: vendor/pugixml
  - url: https://github.com/martinmoene/gsl-lite/archive/913e86d49c6a1acca980f4e325378f9dc393493a.tar.gz
    sha256: 1978f9c6a6c3fffebac174c34d907ad145a5805e01f94b2de433aa5b0e6efdf4
    folder: vendor/gsl-lite
  - url: https://github.com/xtensor-stack/xtensor/archive/0.21.3.tar.gz
    sha256: f63c25cafea4bfc268edb26e6f5004a28a2f689e6a852bb3559c553106c8d6bf
    folder: vendor/xtensor
  - url: https://github.com/xtensor-stack/xtl/archive/0.6.13.tar.gz
    sha256: 12bd628dee4a7a55db79bff5a47fb7d96b1a4dba780fbd5c81c3a15becfdd99c
    folder: vendor/xtl
  - url: https://github.com/fmtlib/fmt/archive/d141cdbeb0fb422a3fb7173b285fd38e0d1772dc.tar.gz
    sha256: 8d2cb0daccef71cbf3ee8068a845fdd379545acd289873e67c41fdc1b530bfcd
    folder: vendor/fmt
  - url: https://github.com/catchorg/Catch2/archive/41990e0fe6274d716134eecfd4d780e976c8fbf5.tar.gz
    sha256: b0ebde3f264a98bd30c08febc11835f3b0252bfea3146eead5792d9d899fa0fc
    folder: vendor/Catch2

build:
  number: {{ build }}
  skip: true  # [win]
  skip: true  # [py<35]
  detect_binary_files_with_prefix: true
  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `openmc * mpi_mpich_*` for mpich
  # `openmc * mpi_*` for any mpi
  # `openmc * nompi_*` for no mpi

  string: {{ mpi_prefix }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - cmake
    - make
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ mpi }}  # [mpi != 'nompi']
    - libgomp    # [linux]
  host:
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - libpng
    - git
    - setuptools
    - pip
    - numpy
    - cython
    - matplotlib-base
    - h5py * {{ mpi_prefix }}_*
    - python
    - {{ mpi }}  # [mpi != 'nompi']
  run:
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - libpng
    - python
    - {{ pin_compatible('numpy') }}
    - h5py * {{ mpi_prefix }}_*
    - scipy
    - pandas
    - matplotlib-base
    - lxml
    - uncertainties
    - setuptools
    - {{ mpi }}  # [mpi != 'nompi']
    - openssh  # [mpi == 'openmpi']
    - ipython
    - njoy2016

test:
  commands:
    - test -f "${PREFIX}/bin/openmc"
    - openmc --version
    - pip check
  imports:
    - openmc
    - openmc.data
    - openmc.deplete
    - openmc.lib
  requires:
    - pip


about:
  home: https://openmc.org
  license: MIT
  license_file: LICENSE
  summary: OpenMC Monte Carlo Code
  description: |
    OpenMC is a community-developed Monte Carlo neutron and photon transport
    simulation code. It is capable of performing fixed source, k-eigenvalue, and
    subcritical multiplication calculations on models built using either a
    constructive solid geometry or CAD representation. OpenMC supports both
    continuous-energy and multigroup transport. The continuous-energy particle
    interaction data is based on a native HDF5 format that can be generated from
    ACE files produced by NJOY. Parallelism is enabled via a hybrid MPI and
    OpenMP programming model.
  doc_url: https://docs.openmc.org
  dev_url: https://github.com/openmc-dev/openmc

extra:
  recipe-maintainers:
    - scopatz
    - paulromano
    - shimwell
    - kkiesling
