{% set org = "openmc-dev" %}
{% set name = "openmc" %}
{% set version = "0.13.0" %}
{% set build = 2 %}

# ensure dagmc is defined (needed for conda-smithy recipe-lint)
{% set dagmc = dagmc or 'nodagmc' %}

{% if dagmc == 'dagmc' %}
# prioritize dagmc variant via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/openmc-dev/{{ name }}.git
  git_rev: v{{ version }}

build:
  number: {{ build }}
  skip: true  # [win]
  skip: true  # [py<35]
  detect_binary_files_with_prefix: true

  # add build string so packages can depend on
  # dagmc or nodagmc variants explicitly:
  # `openmc * nodagmc_*` for openmc without dagmc
  # `openmc * dagmc_*` for openmc with dagmc

  string: {{ dagmc }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - cmake
    - make
    - dagmc 3.2.1  # [dagmc == 'dagmc']
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - dagmc 3.2.1  # [dagmc == 'dagmc']
    - hdf5
    - git
    - setuptools
    - pip
    - numpy
    - cython
    - matplotlib-base
    - h5py
    - python
  run:
    - dagmc 3.2.1  # [dagmc == 'dagmc']
    - hdf5
    - python
    - {{ pin_compatible('numpy') }}
    - h5py
    - scipy
    - pandas
    - matplotlib-base
    - lxml
    - uncertainties
    - setuptools

test:
  commands:
    - test -f "${PREFIX}/bin/openmc"
    - openmc --version
  imports:
    - openmc
    - openmc.data
    - openmc.deplete
    - openmc.lib

about:
  home: https://openmc.org
  license: MIT
  license_file: LICENSE
  summary: OpenMC Monte Carlo Code
  description: |
    OpenMC is a community-developed Monte Carlo neutron and photon transport
    simulation code. It is capable of performing fixed source, k-eigenvalue, and
    subcritical multiplication calculations on models built using either a
    constructive solid geometry or CAD representation. OpenMC supports both
    continuous-energy and multigroup transport. The continuous-energy particle
    interaction data is based on a native HDF5 format that can be generated from
    ACE files produced by NJOY. Parallelism is enabled via a hybrid MPI and
    OpenMP programming model.
  doc_url: https://docs.openmc.org
  dev_url: https://github.com/openmc-dev/openmc

extra:
  recipe-maintainers:
    - scopatz
    - paulromano
    - shimwell
