{% set org = "openmc-dev" %}
{% set name = "openmc" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ org }}/{{ name }}.git
  git_rev: v{{ version }}
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 1
  skip: true  # [win]
  skip: true  # [py<35]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - make
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - hdf5
    - git
    - setuptools
    - pip
    - numpy
    - cython
    - matplotlib-base
    - h5py
    - python
  run:
    - hdf5
    - python
    - {{ pin_compatible('numpy') }}
    - h5py
    - scipy
    - pandas
    - matplotlib-base
    - lxml
    - uncertainties
    - setuptools

test:
  commands:
    - test -f "${PREFIX}/bin/openmc"
    - openmc --version
  imports:
    - openmc
    - openmc.data
    - openmc.deplete
    - openmc.lib

about:
  home: https://openmc.org
  license: MIT
  license_file: LICENSE
  summary: OpenMC Monte Carlo Code
  description: |
    OpenMC is a community-developed Monte Carlo neutron and photon transport
    simulation code. It is capable of performing fixed source, k-eigenvalue, and
    subcritical multiplication calculations on models built using either a
    constructive solid geometry or CAD representation. OpenMC supports both
    continuous-energy and multigroup transport. The continuous-energy particle
    interaction data is based on a native HDF5 format that can be generated from
    ACE files produced by NJOY. Parallelism is enabled via a hybrid MPI and
    OpenMP programming model.
  doc_url: https://docs.openmc.org
  dev_url: https://github.com/openmc-dev/openmc

extra:
  recipe-maintainers:
    - scopatz
    - paulromano
